### ISSUE TITLE
SCC Licence requirements

### ISSUE THREAD

**Issue by lindy63** [google/terraform-google-security-health-checker#1]
Hello there, 

Looks very useful! Just wanted to check if this required an SCC Premium licence to get all the compliance findings?

Cheers!
Lindy

**Comment by jasonbisson** [comment]
Hi Lindy,

You can use the Security Command Center standard version to kick the tires, but there are only 19 findings in Security Health Analytics. However, the standard version should work out if you want a quick test with no cost. 

Thanks for reaching out, and let us know how it goes.

Thanks,

Jason
